project:
  type: website
  output-dir: docs

website:
  title: "CCM & Data-Driven Business Specialist"
  navbar:
    background: dark
    search: true
    left:
      - text: "Inicio"
        href: index.qmd
      - text: "Acerca de mí"
        href: about.qmd
      - text: "Experiencia"
        href: experience.qmd
      - text: "Proyectos"
        menu:
          - text: "Cyclistic"
            href: projects/cyclistic/cyclistic.html
    right: 
      - icon: linkedin
        text: LinkedIn
        href: https://www.linkedin.com/in/adrian-vega-756b3b108

format:
  html:
    theme: slate
    linkcolor: "#2AA63E"
    fontcolor: "#030712"
    toc: false 
    toc-location: right 
    toc-expand: true
    toc-depth: 3
    css: styles.css
    lang: es